### PR TITLE
Optimize pager emails to be more concise

### PR DESCRIPTION
**Pull request by pnaf**
SMS messages should now read better in the span of 3 lines. As a result, all pager emails now have a blank subject.

### CODE REVIEW

**Comment by pnaf** [comment]
Pull request to address #34.

**Comment by pnaf** [comment]
For clarity, the commits in this PR should only affect messages where the `--message-type` is `pager`. Other types such as `email` should be unaffected.

**Comment by RyanFrantz** [comment]
Thanks @pnaf !!

**Comment by pnaf** [comment]
On iOS, pager messages now look like this (notice how summary/extraneous info fits appropriately into the lock screen/SMS, and is less likely to "cut off"):

img_0047
img_0048

**Pull request merged**
